### ISSUE TITLE
[1.16.1] Graphical Glitch - Silver Barrel "Inventory" Label Location

### ISSUE THREAD

**Issue by Aeroneously** [Tfarcenim/MetalBarrels#10]
Using this mod in 1.16.1, I've come across a minor graphical glitch as viewed below:

![image](https://user-images.githubusercontent.com/68843947/88517341-b1158400-cfbc-11ea-99b2-b79f23a1e101.png)

This only appears to occur on the Silver Barrel, no matter the GUI zoom.
I'm very much enjoying working with this mod and look forward to what you bring to the table in the future!
Thank you!

Aeroneously

**Comment by Tfarcenim** [comment]
crob
