### ISSUE TITLE
[1.16.2] contents deleted when barrel upgraded

### ISSUE THREAD

**Issue by bessiq** [Tfarcenim/MetalBarrels#14]
metalbarrels-3.3.jar
Tested on Forge 33.0.37 (modpack: ATM 6 1.0.6) - multiplayer server.
Also tested on Forge 33.0.61 with no other mods installed - singleplayer.

Upgrading from a vanilla barrel causes contents to be deleted. Also tested iron to gold, and gold to diamond, and contents also get deleted.

Latest/debug logs show no new entries after I upgrade and view empty barrel inventory. Let me know if you need any other info. Thanks!

**Comment by Tfarcenim** [comment]
I've got an idea for how to solve this one...

**Comment by Tfarcenim** [comment]
should be fixed
