### ISSUE TITLE
Please checkout crash

### ISSUE THREAD

**Issue by ghost** [Tfarcenim/MetalBarrels#19]
https://github.com/mekanism/Mekanism/issues/7285

**Comment by Tfarcenim** [comment]
Good job

**Comment by ghost** [comment]
Please provide any details of why this is happened if you have some understanding of what is com.tfar.metalbarrels.block.MetalBarrelBlock.func_220052_b(MetalBarrelBlock.java:79)  that cause 
ClassCastException on mekanism.common.tile.transmitter.TileEntityMechanicalPipe
Your sourcecode of class https://github.com/Tfarcenim/MetalBarrels/blob/1.16.x/src/main/java/com/tfar/metalbarrels/block/MetalBarrelBlock.java
differs with the name of function

**Comment by Tfarcenim** [comment]
It was because of mowzie's mobs, all I did was kill a method override.  The names are different because of remapping.
