### ISSUE TITLE
[bug] 1.18.2-4.2 not working correctly ?

### ISSUE THREAD

**Issue by yumekazu** [Tfarcenim/MetalBarrels#25]
Hi o/ !
I've added your mod in its lastest version in my modpack and I've come with weird bugs.
In order to check if it's not my pack the problem, I've created a new instance on forge 40.1.76 with only jei-1.18.2-9.7.1.255 and your mod metalbarrels-1.18.2-4.2 and even asked to a friend to check to be sure and we still both have the same problem.

So, with a 2 scale GUI (or any other scale) Diamond, Silver, Gold and Crystal barrels GUI is completely broken (slots appears off grid too)
![barrelGUIfail](https://user-images.githubusercontent.com/103933552/199242587-2c9aa435-bbc3-4d1d-8b1c-db757f97955e.png)

Iron, Obsidian, Copper and Netherite barrels all have only a double chest inventory
![barrelSlotFail](https://user-images.githubusercontent.com/103933552/199243422-6d427a64-6af6-4f86-9b7b-23323b7994d7.png)

I've no idea where it came from, and I'm honestly surprised that in a mod with nearly 10 millions dl noone I've reported that before so I'm really unsure if it's me or your mod the problem.

**Comment by KeithLerner** [comment]
I am having the exact same problems on the same mod version.
