### ISSUE TITLE
1.18.2 Forge 40.2.0 Quark Sorting GUI Removed, keybing no longer works.

### ISSUE THREAD

**Issue by WDLBPH** [Tfarcenim/MetalBarrels#27]
![image](https://github.com/Tfarcenim/MetalBarrels/assets/75367874/f2342b93-c5b3-4f15-b7a4-6179c1bbd72b)
![image](https://github.com/Tfarcenim/MetalBarrels/assets/75367874/00f34ca0-a342-426c-9ed1-96ee13bfe3a9)
There is a sorting function in quark (using 3.2 538) that can be used with a keybind or a GUI element, pictured above. It used to work in previous versions but in 1.18.2, and I assume onwards, this has dissappeared and doesn't work. Have not tested with other mods that have a sorting function.

**Comment by Tfarcenim** [comment]
This has nothing to do with me, it's on quark.
