### ISSUE TITLE
[1.19.2] Barrels wrongly tagged

### ISSUE THREAD

**Issue by Nycto97** [Tfarcenim/MetalBarrels#30]
The barrels are tagged as `minecraft:mineable_with_pickaxe` while the correct tag is `minecraft:mineable/pickaxe`, causing the blocks to break slowly even with pickaxe efficiency 5.

I fixed it via KubeJS for my server. Just reporting it so it might get fixed for other players.

![image](https://github.com/Tfarcenim/MetalBarrels/assets/83367226/8cda6e80-c031-4924-96be-837142bf0d22)

**Comment by Tfarcenim** [comment]
fixed
