### ISSUE TITLE
fabric 1.21.1 crystal barrel crash

### ISSUE THREAD

**Issue by swe3per** [Tfarcenim/MetalBarrels#32]
Fabric contains sodium lithium. Placing a crystal barrel in version 1.21.1 will cause the game to crash. Since curseforge does not have a corresponding version, I am using version 1.21. I don't know if it is a compatibility issue.

**Comment by Tfarcenim** [comment]
Logs are required.

**Comment by swe3per** [comment]
[crash-2024-10-07_20.52.25-client.txt](https://github.com/user-attachments/files/17278760/crash-2024-10-07_20.52.25-client.txt)
Maybe there is a conflict with tweakroo?

**Comment by Tfarcenim** [comment]
Can't read that

**Comment by swe3per** [comment]
[crash-2024-10-07_20.52.25-client.txt](https://github.com/user-attachments/files/17280026/crash-2024-10-07_20.52.25-client.txt)
sry, here is new log

**Comment by Tfarcenim** [comment]
It's a version mismatch issue, stay on 1.21, I'll have a 1.21.1 eventually but it's a low priority as I am busy.

**Comment by swe3per** [comment]
I'll wait for your update, thank you very much.

**Comment by Crazyminer34** [comment]
in the future make the mod version specific so this doesn't happen, had this same thing happen to me and was confused

**Comment by Tfarcenim** [comment]
fixed in 1.21.1-5
