### ISSUE TITLE
[1.14.3] Server crash when player breaks the barrel when another player has the interface open.

### ISSUE THREAD

**Issue by ProsperCraft** [Tfarcenim/MetalBarrels#4]
https://gist.github.com/ProsperCraft/dbd9a418ee77c02921c52c7d84c30733

Console stacktrace-
https://gist.github.com/ProsperCraft/9dd41920119d5f82c7abf832db1f9811

metalbarrels-1.1a

It may not matter, but the barrel was obtained through a chance globe.

**Comment by Tfarcenim** [comment]
attempted to address this in 1.2a, impossible to test atm

**Comment by Tfarcenim** [comment]
going to take no comment as fixed
